package com.sourav.exceptionhandling;

import java.io.IOException;

public class TestException {
	
	/*TestException() throws IOException{
		
	}
*/
	public static void main(String[] args) {
		try {
			//TestException tx = new TestException();
			 m1();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		//System.out.println(m);
		
	}
	
	public static void m1() /*throws IOException*/{

		System.out.println("");
		/*try{
			int x = 10;
			System.out.println(x/2);
			return x;
			
		}catch(ArithmeticException ex){
			ex.printStackTrace();
		}
		finally{
			System.out.println("Inside finally ..");
			return 23;
		}*/

	
	}

}